### ISSUE TITLE
move repo to tc39 org

### ISSUE THREAD

**Issue by gsathya** [tc39-transfer/set-methods#21]
I don't think I have permissions to move this repo @Ginden @littledan

**Comment by ljharb** [comment]
@Ginden; i've temporarily added you to the tc39-transfer org; you should be able transfer this repo there.

**Comment by littledan** [comment]
I don't have permissions until either @giden does a transfer to tc39-transfers or gives me admin access. From there I could help, just let me know.

**Comment by Ginden** [comment]
@ljharb @littledan @gsathya Transfered to tc39-transfers.

**Comment by littledan** [comment]
Transferred to tc39
